
export const editButton = document.querySelector(".profile__edit-button")
export const profilePopup = document.querySelector("#editProfilePopup")
export const closeButton = document.querySelector("#popup__close-button")
export const indexName = document.querySelector("#input-name")
export const indexAbout = document.querySelector("#input-about")
export const addButton = document.querySelector(".profile__add-button")
export const CardPopup = document.querySelector("#addCardPopup")
export const closeBtnCardPopup = document.querySelector("#close-button-card")
export const indexTitle = document.querySelector("#input-title")
export const indexLink = document.querySelector("#input-link")
export const containerCard = document.querySelector(".elements")
export const placeName = document.querySelector(".element__place-name")
export const elementImage = document.querySelector(".element__image")
export const bigImage = document.querySelector("#PopupImage")
export const buttonCloseImage = document.querySelector("#CloseImagePopup")
export const token = "3aa282d7-9323-433a-907f-6e03563d6d4a"
export const cardOwner = "da4b770da56b5c45647deca1"
export const avatarEditPopup = document.querySelector("#editProfileImg") // popup do avatar
export const avatarEditBtn = document.querySelector(".profile__edit-avatar") // botão de abertura
export const avatarPopupClose = document.querySelector("#popup__avatarClose-button") // botão de fechar avatarPopup
export const avatarLinkInput = document.querySelector("#input-avatar") // input do link avatar
export const avatarSaveBtn = document.querySelector("#profileImg-saveButton") //botão de salavar do avatar popup